//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stenden_Weerstation.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name city from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebAPIController", ReplyAction="*")]
        Stenden_Weerstation.ServiceReference1.WebAPIControllerResponse WebAPIController(Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebAPIController", ReplyAction="*")]
        System.Threading.Tasks.Task<Stenden_Weerstation.ServiceReference1.WebAPIControllerResponse> WebAPIControllerAsync(Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebAPIControllerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebAPIController", Namespace="http://tempuri.org/", Order=0)]
        public Stenden_Weerstation.ServiceReference1.WebAPIControllerRequestBody Body;
        
        public WebAPIControllerRequest() {
        }
        
        public WebAPIControllerRequest(Stenden_Weerstation.ServiceReference1.WebAPIControllerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WebAPIControllerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        public WebAPIControllerRequestBody() {
        }
        
        public WebAPIControllerRequestBody(string city, string apiKey) {
            this.city = city;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebAPIControllerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebAPIControllerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Stenden_Weerstation.ServiceReference1.WebAPIControllerResponseBody Body;
        
        public WebAPIControllerResponse() {
        }
        
        public WebAPIControllerResponse(Stenden_Weerstation.ServiceReference1.WebAPIControllerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WebAPIControllerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WebAPIControllerResult;
        
        public WebAPIControllerResponseBody() {
        }
        
        public WebAPIControllerResponseBody(string WebAPIControllerResult) {
            this.WebAPIControllerResult = WebAPIControllerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Stenden_Weerstation.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Stenden_Weerstation.ServiceReference1.WebService1Soap>, Stenden_Weerstation.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Stenden_Weerstation.ServiceReference1.WebAPIControllerResponse Stenden_Weerstation.ServiceReference1.WebService1Soap.WebAPIController(Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest request) {
            return base.Channel.WebAPIController(request);
        }
        
        public string WebAPIController(string city) {
            Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest inValue = new Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest();
            inValue.Body = new Stenden_Weerstation.ServiceReference1.WebAPIControllerRequestBody();
            inValue.Body.city = city;
            Stenden_Weerstation.ServiceReference1.WebAPIControllerResponse retVal = ((Stenden_Weerstation.ServiceReference1.WebService1Soap)(this)).WebAPIController(inValue);
            return retVal.Body.WebAPIControllerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Stenden_Weerstation.ServiceReference1.WebAPIControllerResponse> Stenden_Weerstation.ServiceReference1.WebService1Soap.WebAPIControllerAsync(Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest request) {
            return base.Channel.WebAPIControllerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Stenden_Weerstation.ServiceReference1.WebAPIControllerResponse> WebAPIControllerAsync(string city, string apiKey) {
            Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest inValue = new Stenden_Weerstation.ServiceReference1.WebAPIControllerRequest();
            inValue.Body = new Stenden_Weerstation.ServiceReference1.WebAPIControllerRequestBody();
            inValue.Body.city = city;
            inValue.Body.apiKey = apiKey;
            return ((Stenden_Weerstation.ServiceReference1.WebService1Soap)(this)).WebAPIControllerAsync(inValue);
        }
    }
}
